### PR TITLE
Add *HELP, *TYPE, *CLS, *MOUNT Commands

### PR DESCRIPTION
**Pull request by leighbb**
In order to make a more comfortable MOS environment, I have added the following commands:
*HELP - Display help on commands
*TYPE - Like the equivalent DOS command, displays a text file on the console
*CLS - shortcut to VDU 12 (which not all users may be familiar with)
*MOUNT - Re-(mount) the MicroSD card

Happy for any feedback.

### CODE REVIEW

**Comment by leighbb** [comment]
Example showing use of MOUNT after MicroSD card removed and re-inserted:
image

**Comment by leighbb** [comment]
Example showing *HELP ALL:
image

**Comment by leighbb** [comment]
Finally, using the TYPE command to display a text file:
image

**Comment by leventp** [comment]
This looks good. I think the '*' char should not be displayed in the help text. After all , it is the MOS prompt and not needed to be typed  in, and making the text a bit confusing.

**Comment by leighbb** [comment]
> This looks good. I think the '*' char should not be displayed in the help text. After all , it is the MOS prompt and not needed to be typed in, and making the text a bit confusing.

Fair enough - updated patch to remove the *'s

**Comment by breakintoprogram** [comment]
Hi, this has been merged as part of pull request #93 so am closing as it is now done.

**Comment by breakintoprogram** [comment]
Hi, this has been merged as part of pull request #93 so am closing as it is now done.

**Pull request closed without merging**
